db:
  pvcname: db-pvc
  pvstorage: 1Gi
  dbdeploymentname: db-deployment
  dbreplicas: 1
  dbpodselector: db
  dbcontainername: db
  dbimage:
    repository: mongo
    tag: "latest"
  dbvolumename: db-storage
  dbmountpath: /data/db
  dbservicename: db

backend:
  backendnamespace: backendnamespace
  backendconfigmapname: backendconfigmap
  backendsecretname: backendsecret
  backenddeploymentname: backend-deployment
  backendreplicas: 2
  backendpodselector: backend
  backendcontainername: backend
  backendimage:
    repository: doomerdpk/argobackend
    tag: 20f6e08446647f40d79f75b079cc1763416f1c7b
  backendsecretvolumename: env-file
  backendsecretmountpath: /app/secrets
  backendservicename: backend

frontend:
  frontendnamespace: frontendnamespace
  frontenddeploymentname: frontend-deployment
  frontendreplicas: 1
  frontendpodselector: frontend
  frontendcontainername: frontend
  frontendimage:
    repository: doomerdpk/argofrontend
    tag: 20f6e08446647f40d79f75b079cc1763416f1c7b
  frontendservicename: frontend

ingress:
  frontendingressname: frontendingress
  backendingressname: backendingress
  ingresshost: k8s.deepak.cfd
  frontendnamespace: frontendnamespace
  frontendservicename: frontend
  backendnamespace: backendnamespace
  backendservicename: backend
