db:
  pvcname: db-pvc
  pvstorage: 1Gi
  dbdeploymentname: db-deployment
  dbreplicas: 1
  dbpodselector: db
  dbcontainername: db
  dbimage:
    repository: mongo
    tag: "latest"
  dbvolumename: db-storage
  dbmountpath: /data/db
  dbservicename: db

backend:
  backendnamespace: backendnamespace
  backendconfigmapname: backendconfigmap
  backendsecretname: backendsecret
  backenddeploymentname: backend-deployment
  backendreplicas: 2
  backendpodselector: backend
  backendcontainername: backend
  backendimage:
    repository: doomerdpk/argobackend
    tag: db7b96049ae21c946eeb40050c5e636c2b33be30
    tag: "9e22909bb356c146e6502f0021dcaf1b6ffc3801"
  backendsecretvolumename: env-file
  backendsecretmountpath: /app/secrets
  backendservicename: backend

frontend:
  frontendnamespace: frontendnamespace
  frontenddeploymentname: frontend-deployment
  frontendreplicas: 1
  frontendpodselector: frontend
  frontendcontainername: frontend
  frontendimage:
    repository: doomerdpk/argofrontend
    tag: db7b96049ae21c946eeb40050c5e636c2b33be30
    tag: "9e22909bb356c146e6502f0021dcaf1b6ffc3801"
  frontendservicename: frontend

ingress:
  frontendingressname: frontendingress
  backendingressname: backendingress
  ingresshost: k8s.deepak.cfd
  frontendnamespace: frontendnamespace
  frontendservicename: frontend
  backendnamespace: backendnamespace
  backendservicename: backend
